on: [push]
jobs:
  mail_on_push:
    runs-on: ubuntu-latest
    steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Send Mail
        body: "tuvipost on kiirem, aga commiti tegi" + ${{github.event.pusher.name}} + ${{github.repository}} + " sonumiga " + ${{github.event.head_commit.message}}
        to: pia.lember@gmail.com
        from: Github actions
        
